# Quiz Generator Configuration
quiz_generate:
  name: quiz generator
  description: >
      Analyze the following technical content and generate a high-quality quiz:
      CONTENT:
      {text}
      REQUIREMENTS:
      1. Generate exactly 10 MCQs covering key concepts
      2. Ensure questions progress from basic to advanced
      3. Each question must have:
      - Clear question with complete phrasing
      - 4 plausible distractors
      - One unambiguous correct answer
      - Output strict JSON format 
  expected_output: >
    JSON object containing 10 MCQs following the specified format.
    Ensure proper escaping for JSON validity.
  output_file: E:\DATA SCIENCE\projects\Agents\01-Quiz generator\output\generated_quiz.json #os.path.join(OUTPUT_PATH, "generated_quiz.json


# Quiz Analyzer Configuration
quiz_analysis:
  name: Quiz Question Analysis
  description: >
    Process multiple-choice (MCQ) quiz questions by explaining
    the question, providing detailed feedback on each answer option, and suggesting
    related topics for further study.
    Takes the output of the previous quiz_generator agent, which provides the quiz questions
    along with the correct answer index, as context.
  expected_output: >
    JSON object following the specified format.
    Ensure proper escaping for JSON validity.
  context: >
    - quiz_generator
  output_file: E:\DATA SCIENCE\projects\Agents\01-Quiz generator\output\quiz_analysis.json
